2024-04-19 10:15:30 - ERROR - Exception occurred in function 'handle_request': KeyError: 'user_id'
Traceback (most recent call last):
  File "app.py", line 56, in handle_request
    user_id = request.json['user_id']
KeyError: 'user_id'

2024-04-23 11:24:23,292 - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:8000
2024-04-23 11:24:23,292 - INFO - [33mPress CTRL+C to quit[0m
2024-04-23 11:24:23,292 - INFO -  * Restarting with stat
2024-04-23 11:24:23,551 - WARNING -  * Debugger is active!
2024-04-23 11:24:23,560 - INFO -  * Debugger PIN: 403-181-477
2024-04-23 11:24:32,998 - INFO - 127.0.0.1 - - [23/Apr/2024 11:24:32] "GET / HTTP/1.1" 200 -
2024-04-23 11:24:33,023 - INFO - 127.0.0.1 - - [23/Apr/2024 11:24:33] "GET /swaggerui/swagger-ui.css HTTP/1.1" 200 -
2024-04-23 11:24:33,025 - INFO - 127.0.0.1 - - [23/Apr/2024 11:24:33] "GET /swaggerui/droid-sans.css HTTP/1.1" 200 -
2024-04-23 11:24:33,027 - INFO - 127.0.0.1 - - [23/Apr/2024 11:24:33] "GET /swaggerui/swagger-ui-bundle.js HTTP/1.1" 200 -
2024-04-23 11:24:33,028 - INFO - 127.0.0.1 - - [23/Apr/2024 11:24:33] "GET /swaggerui/swagger-ui-standalone-preset.js HTTP/1.1" 200 -
2024-04-23 11:24:33,227 - INFO - 127.0.0.1 - - [23/Apr/2024 11:24:33] "GET /swaggerui/favicon-32x32.png HTTP/1.1" 200 -
2024-04-23 11:24:33,260 - INFO - 127.0.0.1 - - [23/Apr/2024 11:24:33] "GET /swagger.json HTTP/1.1" 200 -
2024-04-23 11:24:33,262 - INFO - 127.0.0.1 - - [23/Apr/2024 11:24:33] "[36mGET /swaggerui/favicon-32x32.png HTTP/1.1[0m" 304 -
2024-04-23 11:26:13,766 - ERROR - Error fetching user by account ID ' ': ac-r79gfle-shard-00-02.9laqhsg.mongodb.net:27017: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1002) (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms),ac-r79gfle-shard-00-01.9laqhsg.mongodb.net:27017: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1002) (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms),ac-r79gfle-shard-00-00.9laqhsg.mongodb.net:27017: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1002) (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms), Timeout: 30s, Topology Description: <TopologyDescription id: 6627d2f7c36ab86d968c2623, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('ac-r79gfle-shard-00-00.9laqhsg.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('ac-r79gfle-shard-00-00.9laqhsg.mongodb.net:27017: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1002) (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>, <ServerDescription ('ac-r79gfle-shard-00-01.9laqhsg.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('ac-r79gfle-shard-00-01.9laqhsg.mongodb.net:27017: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1002) (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>, <ServerDescription ('ac-r79gfle-shard-00-02.9laqhsg.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('ac-r79gfle-shard-00-02.9laqhsg.mongodb.net:27017: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1002) (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>
2024-04-23 11:26:13,793 - INFO - 127.0.0.1 - - [23/Apr/2024 11:26:13] "[35m[1mGET /users/account/%20 HTTP/1.1[0m" 500 -
